# We need a decent ubuntu dist
sudo: required
dist: trusty

# Modern cpp settings from
#  http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
      env: COMPILER=g++-5

before_install:
  - pip install --user cpp-coveralls
  - sudo -H pip install --upgrade requests[security]
install:
  # Install OpenCV dependencies and package
  - sudo apt-get install -y -qq lcov
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libjpeg8-dev libpng-dev
  - sudo apt-get install -y libjasper1 libtiff-dev libxine2-dev libv41-dev
  - sudo apt-get install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
  - sudo apt-get install -y libgtk2.0-dev libtbb-dev qt5-default
  - sudo apt-get install -y libatlas-base-dev
  - sudo apt-get install -y libfaac-dev libmp3lame-dev libtheora-dev
  - sudo apt-get install -y libvorbis-dev libxvidcore-dev
  - sudo apt-get install -y libopencore-amrnb-dev libopencore-amrwb-dev
  - sudo apt-get install -y libavresample-dev
  - sudo apt-get install -y x264 v4l-utils
  - git clone https://github.com/opencv/opencv.git
  - git clone https://github.com/opencv/opencv_contrib.git
  - cd opencv
  
  # Create a new 'build' folder
  - mkdir build
  - cd build

  # set build instructions for Ubuntu
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D OPENCV_EXTRA_MODULES_PATH = ../../opencv_contrib/modules -D WITH_TBB=ON -D BUILD_EXAMPLES=OFF -D BUILD_DOCS=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D WITH_QT=ON -D WITH_OPENGL=ON ..

  # Run 'make' with 8 threads.
  - make -j4
  - sudo make install

  # Add configuration to OpenCV
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldcongif
  - echo "OpenCV Installed."


script:
  - export CXX=$COMPILER;
  - mkdir build
  - cd build
  - cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
  - make
  - make code_coverage
  - test/cpp-test

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
